apiVersion: v2
name: alvin
description: A Helm chart for Alvin on Kubernetes
type: application
version: 0.30.0
appVersion: 0.38.0
dependencies:
  - name: cora
    version: 4.3.0
    repository: file://../cora
