apiVersion: v2
name: alvin
description: A Helm chart for Alvin on Kubernetes
type: application
version: 0.13.0
appVersion: 0.21.0
dependencies:
  - name: cora
    version: 3.8.0
    repository: file://../cora
