apiVersion: v2
name: alvin
description: A Helm chart for Alvin on Kubernetes
type: application
version: 0.64.0
appVersion: 0.72.0
dependencies:
  - name: cora
    version: 4.15.0
    repository: file://../cora
