apiVersion: v2
name: diva
description: A Helm chart for DiVA on Kubernetes
type: application
version: 0.10.122
appVersion: 1.20.0
dependencies:
  - name: cora
    version: 3.7.0
    repository: file://../cora
