apiVersion: v2
name: diva
description: A Helm chart for DiVA on Kubernetes
type: application
version: 0.189.0
appVersion: "2026.3"
dependencies:
  - name: cora
    version: 4.16.0
    repository: file://../cora
