apiVersion: v2
name: diva
description: A Helm chart for DiVA on Kubernetes
type: application
version: 0.194.0
appVersion: 2026.4-dev
dependencies:
  - name: cora
    version: 4.17.0
    repository: file://../cora
