{{- define "cora-binaryconverter.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.system.name }}-binaryconverter-{{ .Values.binaryConverter.subName }}-deployment
  labels:
    app: {{ .Values.system.name }}-binaryconverter-{{ .Values.binaryConverter.subName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.system.name }}-binaryconverter-{{ .Values.binaryConverter.subName }}
  template:
    metadata:
      labels:
        app: {{ .Values.system.name }}-binaryconverter-{{ .Values.binaryConverter.subName }}
    spec:
      initContainers:
        {{- toYaml .Values.initContainers.waitForMq | nindent 6 }}
      containers:
      - name: {{ .Values.system.name }}-binaryconverter-{{ .Values.binaryConverter.subName }}
        image: {{ .Values.dockerRepository.url }}cora-docker-binaryconverter:1.0-SNAPSHOT
        env:
        - name: coraBaseUrl
          value: "http://{{ .Values.system.name }}:8080/{{ .Values.system.name }}/rest/"
        - name: apptokenVerifierUrl
          value: "http://login:8080/login/rest/"
        - name: loginId
          value: "systemoneAdmin@system.cora.uu.se"
        - name: appToken
          value: "5d3f3ed4-4931-4924-9faa-8eaf5ac6457e"
        - name: rabbitMqHostName
          value: "{{ .Values.system.name }}-rabbitmq"
        - name: rabbitMqPort
          value: "5672"
        - name: rabbitMqVirtualHost
          value: "/"
        - name: rabbitMqQueueName
          value: {{ .Values.binaryConverter.queueName }}
        - name: fedoraOcflHome
          value: "/tmp/sharedArchiveReadable/systemOne"
        - name: fileStorageBasePath
          #is the last slash needed?
          value: "/tmp/sharedFileStorage/systemOne/"
        volumeMounts:
        - mountPath: "/tmp/sharedArchiveReadable/systemOne"
          name: archive-read-only
          readOnly: true
        - mountPath: "/tmp/sharedFileStorage/systemOne"
          name: converted-files-read-write
      volumes:
        - name: archive-read-only
          persistentVolumeClaim:
            claimName: {{ .Values.system.name }}-archive-read-only-volume-claim
        - name: converted-files-read-write
          persistentVolumeClaim:
            claimName: {{ .Values.system.name }}-converted-files-read-write-volume-claim
      imagePullSecrets:
      - name: cora-dockers
---
{{- end }}

