apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemone-solr-deployment
  labels:
    app: systemone-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systemone-solr
  template:
    metadata:
      labels:
        app: systemone-solr
    spec:
      containers:
      - name: systemone-solr
        image: {{ .Values.dockerRepository.url }}cora-solr:1.0-SNAPSHOT
        ports:
        - containerPort: 8983
        args: ["solr-precreate", "coracore", "/opt/solr/server/solr/configsets/coradefaultcore"]
      imagePullSecrets:
      - name: cora-dockers

---
apiVersion: v1
kind: Service
metadata:
  name: solr
spec:
  selector:
    app: systemone-solr
  ports:
    - protocol: TCP
      port: 8983
      targetPort: 8983
