#postgresql

#pvSharedArchive #ReadWriteMany
#pvcSharedArchiveReadWrite #ReadWriteMany
#pvcSharedArchiveReadOnly #ReadOnlyMany

#pvConvertedFiles #ReadWriteMany
#pvcConvertedFilesReadWrite #ReadWriteMany
#pvcConvertedFilesReadOnly #ReadOnlyMany

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: systemone-postgres-volume-claim
  labels:
    app: systemone-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: systemone-archive-read-write-volume-claim
  labels:
    app: systemone-archive
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: systemone-archive-read-only-volume-claim
  labels:
    app: systemone-archive-read-only-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: systemone-converted-files-read-write-volume-claim
  labels:
    app: systemone-converted-files
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: systemone-converted-files-read-only-volume-claim
  labels:
    app: systemone-converted-files-read-only-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi

---
