apiVersion: v1
kind: Secret
metadata:
  name: systemone-secret
type: Opaque
data:
  POSTGRES_DB: c3lzdGVtb25l
  POSTGRES_USER: c3lzdGVtb25l
  POSTGRES_PASSWORD: c3lzdGVtb25l
#  DATA_DIVIDERS: Y29yYSBqc0NsaWVudCBzeXN0ZW1PbmUgdGVzdFN5c3RlbQ==


#echo -n 'Hello, World!' | base64

#echo -n "your-secure-password" | base64
