apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: systemone-rabbitmq-deployment
  labels:
    app: systemone-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systemone-rabbitmq
  template:
    metadata:
      labels:
        app: systemone-rabbitmq
    spec:
      containers:
      - name: systemone-rabbitmq
        image: {{ .Values.dockerRepository.url }}cora-docker-rabbitmq:1.0-SNAPSHOT
        ports:
        - containerPort: 5672
      imagePullSecrets:
      - name: cora-dockers

---
apiVersion: v1
kind: Service
metadata:
  name: systemone-rabbitmq
spec:
  type: NodePort
  selector:
    app: systemone-rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
