apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: systemone-postgresql-deployment
  labels:
    app: systemone-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systemone-postgresql
  template:
    metadata:
      labels:
        app: systemone-postgresql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: systemone-postgresql
        image: {{ .Values.dockerRepository.url }}systemone-docker-postgresql:1.0-SNAPSHOT
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: systemone-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: systemone-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: systemone-secret
              key: POSTGRES_PASSWORD
        - name: DATA_DIVIDERS
          valueFrom:
            configMapKeyRef:
              name: systemone-config
              key: dataDividers
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgresql-volume
      volumes:
        - name: postgresql-volume
          persistentVolumeClaim:
            claimName: {{ .Values.system.name }}-postgres-volume-claim
      imagePullSecrets:
      - name: cora-dockers

---
apiVersion: v1
kind: Service
metadata:
  #name: systemone-postgresql-service
  name: systemone-postgresql
spec:
  selector:
    #app.kubernetes.io/name: systemone-postgresql
    app: systemone-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432




