{{- if .Values.deployFitNesse }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemone-fitnesse-deployment
  labels:
    app: systemone-fitnesse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systemone-fitnesse
  template:
    metadata:
      labels:
        app: systemone-fitnesse
    spec:
      containers:
      - name: systemone-fitnesse
        image: {{ .Values.dockerRepository.url }}systemone-docker-fitnesse:1.1-SNAPSHOT
        ports:
        - containerPort: 8090
        volumeMounts:
        - mountPath: "/tmp/sharedArchiveReadable/systemOne"
          name: archive-read-only
          readOnly: true
          #recursiveReadOnly: Enabled
        - mountPath: "/tmp/sharedFileStorage/systemOne"
          name: converted-files-read-write
      volumes:
        - name: archive-read-only
          persistentVolumeClaim:
            claimName: {{ .Values.system.name }}-archive-read-only-volume-claim
        - name: converted-files-read-write
          persistentVolumeClaim:
            claimName: {{ .Values.system.name }}-converted-files-read-only-volume-claim
      imagePullSecrets:
      - name: cora-dockers


---

apiVersion: v1
kind: Service
metadata:
  name: fitnesse
spec:
  type: NodePort
  selector:
    app: systemone-fitnesse
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30580
{{- end }}