apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemone-rest-deployment
  labels:
    app: systemone-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systemone-rest
  template:
    metadata:
      labels:
        app: systemone-rest
    spec:
      initContainers:
        {{- toYaml .Values.initContainers.waitForDb | nindent 6 }}
      initContainers:
        {{- toYaml .Values.initContainers.waitForMq | nindent 6 }}
      containers:
      - name: systemone-rest
        image: {{ .Values.dockerRepository.url }}systemone-docker:1.0-SNAPSHOT
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/mnt/data/basicstorage"
          name: converted-files-read-write
      volumes:
        - name: converted-files-read-write
          persistentVolumeClaim:
            claimName: {{ .Values.system.name }}-converted-files-read-write-volume-claim
      imagePullSecrets:
      - name: cora-dockers

---

apiVersion: v1
kind: Service
metadata:
  name: systemone
spec:
  type: NodePort
  selector:
    app: systemone-rest
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.port.rest }}
