{{- if .Values.deployJsClient }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemone-jsclient-deployment
  labels:
    app: systemone-jsclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systemone-jsclient
  template:
    metadata:
      labels:
        app: systemone-jsclient
    spec:
      containers:
      - name: cora-docker-jsclient
        #systemone-jsclient
        #image: cora-docker-jsclient:1.0-SNAPSHOT
        #for local image
        #imagePullPolicy: Never

        image: {{ .Values.dockerRepository.url }}cora-docker-jsclient:1.0-SNAPSHOT
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: cora-dockers

---

apiVersion: v1
kind: Service
metadata:
  name: systemone-jsclient-service
spec:
  type: NodePort
  selector:
    app: systemone-jsclient
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30280
{{- end }}