{{- if .Values.deploy.divaclient }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.system.name }}-divaclient-deployment
  labels:
    app: {{ .Values.system.name }}-divaclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.system.name }}-divaclient
  template:
    metadata:
      labels:
        app: {{ .Values.system.name }}-divaclient
    spec:
      containers:
      - name: {{ .Values.system.name }}-divaclient
        image: {{ .Values.cora.dockerRepository.url }}{{ .Values.docker.divaclient }}
        env:
        - name: CORA_API_URL
          value: "http://apache/rest"
        - name: CORA_LOGIN_URL
          value: "http://apache/login/rest"
        - name: CORA_EXTERNAL_SYSTEM_URL
          value: {{ .Values.externalAccess.systemUrl }}
        - name: BASE_PATH
          value: {{ .Values.externalAccess.divaClientBasePath}}
        - name: SESSION_SECURE
          value: {{ .Values.security.divaClientSecureSessionCookie | quote }}
        - name: SESSION_SECRETS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.system.name }}-secret
              key: divaClientSessionCookieSecrets
        ports:
        - containerPort: 5173
      {{- if .Values.cora.dockerRepository.useImagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.cora.dockerRepository.imagePullSecrets }}
      {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.system.name }}-divaclient
spec:
  selector:
    app: {{ .Values.system.name }}-divaclient
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173

{{- end }}

