dockerRepository:
  url: docker.epc.ub.uu.se/
  useImagePullSecrets: false
  imagePullSecrets: someImagePullSecret
initContainer:
  waitForDb:
    - name: init-wait-for-db
      image: postgres:18-alpine
      command: ['sh', '-c', 
        'until pg_isready -h postgresql -p 5432; 
        do echo waiting for database; sleep 2; done;']
  waitForMq:
    - name: init-wait-for-mq
      image: alpine
      command:
        - sh
        - -c
        - until nc -z -v -w1 rabbitmq 5672; do echo "Waiting for RabbitMQ..";
          sleep 5; done