#postgresql

#pvSharedArchive #ReadWriteMany
#pvcSharedArchiveReadWrite #ReadWriteMany
#pvcSharedArchiveReadOnly #ReadOnlyMany

#pvConvertedFiles #ReadWriteMany
#pvcConvertedFilesReadWrite #ReadWriteMany
#pvcConvertedFilesReadOnly #ReadOnlyMany


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alvin-postgres-volume-claim
  labels:
    app: alvin-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alvin-archive-read-write-volume-claim
  labels:
    app: alvin-archive
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alvin-converted-files-read-write-volume-claim
  labels:
    app: alvin-converted-files
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alvin-credentials-read-write-volume-claim
  labels:
    app: alvin-credentials-read-write-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: alvin-postgres-volume
  labels:
    type: local
    app: alvin-postgres
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/alvin/postgresql
  claimRef:
    namespace: alvin
    name: alvin-postgres-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: alvin-archive-volume
  labels:
    type: local
    app: alvin-archive
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/alvin/archive
  claimRef:
    namespace: alvin
    name: alvin-archive-read-write-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: alvin-converted-files-volume
  labels:
    type: local
    app: alvin-converted-files
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/alvin/convertedFiles
  claimRef:
    namespace: alvin
    name: alvin-converted-files-read-write-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: alvin-credentials-read-write-volume
  labels:
    type: local
    app: alvin-credentials
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/alvin/certificates/shibboleth/local
  claimRef:
    namespace: alvin
    name: alvin-credentials-read-write-volume-claim
---