deploy:
  fitnesse: true
  jsclient: false

externalAccess:
  loginPath: /diva/login/rest/
  systemUrl: https://cora.epc.ub.uu.se
  logoutUrl: https://cora.epc.ub.uu.se/diva/login/rest/authToken/
  restUrl: http://cora.epc.ub.uu.se/diva/rest
  loginRestUrl: http://cora.epc.ub.uu.se/diva/login/rest
  divaClientBasePath: /divaclient

port:
  rest: 31082
  login: 31182
  jsclient: 31282
  idplogin: 31382
  fitnesse: 31582
  divaclient: 31682