#postgresql

#pvSharedArchive #ReadWriteMany
#pvcSharedArchiveReadWrite #ReadWriteMany
#pvcSharedArchiveReadOnly #ReadOnlyMany

#pvConvertedFiles #ReadWriteMany
#pvcConvertedFilesReadWrite #ReadWriteMany
#pvcConvertedFilesReadOnly #ReadOnlyMany

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: systemone-postgres-volume
  labels:
    type: local
    app: systemone-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/depot/nfs_vm_cluster/systemone/postgresql
    #server: 192.168.0.192
    server: nfs-vm-cluster
  persistentVolumeReclaimPolicy: Retain
  #hostPath:
  #  path: /mnt/minikube/systemone/postgresql
  claimRef:
    namespace: helm-systemone
    name: systemone-postgres-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: systemone-archive-volume
  labels:
    type: local
    app: systemone-archive
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/depot/nfs_vm_cluster/systemone/archive
    #server: 192.168.0.192
    server: nfs-vm-cluster
  persistentVolumeReclaimPolicy: Retain
  #hostPath:
  #  path: /mnt/minikube/systemone/archive
  claimRef:
    namespace: helm-systemone
    name: systemone-archive-read-write-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: systemone-archive-read-only-volume
  labels:
    type: local
    app: systemone-archive
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /mnt/depot/nfs_vm_cluster/systemone/archive
    #server: 192.168.0.192
    server: nfs-vm-cluster
  persistentVolumeReclaimPolicy: Retain
  #hostPath:
  #  path: /mnt/minikube/systemone/archive
  claimRef:
    namespace: helm-systemone
    name: systemone-archive-read-only-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: systemone-converted-files-volume
  labels:
    type: local
    app: systemone-converted-files
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/depot/nfs_vm_cluster/systemone/convertedFiles
    #server: 192.168.0.192
    server: nfs-vm-cluster
  persistentVolumeReclaimPolicy: Retain
  #hostPath:
  #  path: /mnt/minikube/systemone/convertedFiles
  claimRef:
    namespace: helm-systemone
    name: systemone-converted-files-read-write-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: systemone-converted-files-read-only-volume
  labels:
    type: local
    app: systemone-converted-files
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /mnt/depot/nfs_vm_cluster/systemone/convertedFiles
    #server: 192.168.0.192
    server: nfs-vm-cluster
  persistentVolumeReclaimPolicy: Retain
  #hostPath:
  #  path: /mnt/minikube/systemone/convertedFiles
  claimRef:
    namespace: helm-systemone
    name: systemone-converted-files-read-only-volume-claim
---
