deploy:
  fitnesse: true
  jsclient: false

externalAccess:
  loginPath: /systemone/login/rest/
  systemUrl: https://cora.epc.ub.uu.se
  logoutUrl: https://cora.epc.ub.uu.se/systemone/login/rest/authToken/

port:
  rest: 31080
  login: 31180
  jsclient: 31280
  idplogin: 31380
  fitnesse: 31580